name: Pixel Update Issue Check

on:
  issues:
    types: [opened]

jobs:
  check-issue-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue title starts with 'pixel update:'
        run: |
          TITLE="${{ github.event.issue.title }}"
          if [[ "$TITLE" != pixel\ update:* ]]; then
            echo "Issue title must start with 'pixel update:'"
            exit 1
          fi
          echo "Issue title is valid."
