name: Pixel Update Issue Check

on:
  issues:
    types: [opened]

jobs:
  update-pixel:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pillow

      - name: Parse issue title and run update_grid.py
        id: parse_and_update
        run: |
          TITLE="${{ github.event.issue.title }}"
          if [[ ! "$TITLE" =~ ^pixel\ update:[[:space:]]+([0-9]+)[[:space:]]+([0-9]+)[[:space:]]+(#[0-9A-Fa-f]{6})$ ]]; then
            echo "Issue title must be in the format: pixel update: x y #RRGGBB"
            exit 1
          fi
          X=$(echo "$TITLE" | awk '{print $3}')
          Y=$(echo "$TITLE" | awk '{print $4}')
          COLOR=$(echo "$TITLE" | awk '{print $5}')
          echo "Parsed values: x=$X, y=$Y, color=$COLOR"
          python3 update_grid.py "$X" "$Y" "$COLOR"

      - name: Close issue if successful
        if: success()
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "Pixel update applied and image updated. Issue closed automatically."
      - name: Commit and push grid changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add grid.json grid.png
          git commit -m "Update grid for $TITLE from issue #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push
